env: doom_benchmark
run: CUSTOM_APPO
config:
    lr: 0.0001
    lambda: 0.95
#    kl_coeff: 0.5
    clip_rewards: False
    clip_param: 0.1
    entropy_coeff: 0.0005
    train_batch_size: 2048
    sample_batch_size: 32
    num_sgd_iter: 1
    num_workers: 1
    num_envs_per_worker: 1
    batch_mode: truncate_episodes
    observation_filter: NoFilter
    num_gpus: 1

    compress_observations: False  # this didn't seem to work in this version of RLLIB

    num_data_loader_buffers: 1
    minibatch_buffer_size: 1
    replay_proportion: 0.0
    replay_buffer_num_slots: 0

    model:
        custom_model: vizdoom_vision_model
        conv_filters: [
            [32, [8, 8], 4],
            [64, [4, 4], 2],
            [128, [3, 3], 2],
        ]
        conv_activation: elu
        fcnet_activation: elu  # same as sample factory

        use_lstm: False
        max_seq_len: 16
        lstm_cell_size: 256
        lstm_use_prev_action_reward: False
        framestack: False
        grayscale: False
        zero_mean: False

    env_config:
        skip_frames: 4
        res_w: 128
        res_h: 72
        wide_aspect_ratio: False
