env: doom_battle
run: IMPALA
stop:
    time_total_s: 30000000
config:
    lr: 0.0001
    gamma: 0.99
    clip_rewards: False
    entropy_coeff: 0.001
    train_batch_size: 2048
    sample_batch_size: 32
    num_sgd_iter: 1
    num_workers: 20
    num_envs_per_worker: 10
    batch_mode: truncate_episodes
    num_cpus_per_worker: 0.5  # this allows to create 1 actor per core
    observation_filter: NoFilter
    num_gpus: 1

    num_data_loader_buffers: 1
    minibatch_buffer_size: 1
    replay_proportion: 0.0
    replay_buffer_num_slots: 0

    model:
        custom_model: vizdoom_vision_model
        conv_filters: [
            [32, [8, 8], 4],
            [64, [4, 4], 2],
            [64, [3, 3], 2],
            [128, [3, 3], 2],
        ]
        conv_activation: elu
        fcnet_activation: elu  # was tanh

        use_lstm: True
        max_seq_len: 32
        lstm_cell_size: 512
        lstm_use_prev_action_reward: False
        framestack: False
        grayscale: False
        zero_mean: False

    env_config:
        skip_frames: 4
        res_w: 128
        res_h: 72
        wide_aspect_ratio: False
