env: doom_dwango5_bots_hybrid
run: CUSTOM_APPO
stop:
    time_total_s: 10800
config:
    lr: 0.0001
    lambda: 0.95
    kl_coeff: 0.5
    clip_rewards: False
    clip_param: 0.1
    entropy_coeff:
        grid_search: [0.0002, 0.0005, 0.001]
    train_batch_size:
        grid_search: [1024, 2048]
    sample_batch_size: 128
    num_sgd_iter:
        grid_search: [4, 8]
    num_workers: 18
    num_envs_per_worker: 8
    batch_mode: truncate_episodes
    observation_filter: NoFilter
    num_gpus: 1

    num_data_loader_buffers: 1
    minibatch_buffer_size: 1
    replay_proportion: 0.0
    replay_buffer_num_slots: 0

    model:
        custom_model: vizdoom_vision_model
        conv_filters: [
            [32, [8, 8], 4],
            [64, [4, 4], 2],
            [64, [3, 3], 2],
            [128, [3, 3], 2],
        ]
        conv_activation:
            grid_search: [elu, relu]
        fcnet_activation:
            grid_search: [elu, relu]
        use_lstm: False
        max_seq_len: 16
        lstm_cell_size: 256
        lstm_use_prev_action_reward: False
        framestack: False
        grayscale: False
        zero_mean: False
